In [6]:
import pandas as pd
import numpy as np
ds=pd.Series([10,20,30,40,50],index=['v','h','a','b','j'],dtype='float',name='va')
ds

v    10.0
h    20.0
a    30.0
b    40.0
j    50.0
Name: va, dtype: float64

In [8]:
import pandas as pd
import numpy as np
ds=pd.Series((10,20,30,40,50),index=['v','h','a','b','j'],dtype='float',name='va')
ds

v    10.0
h    20.0
a    30.0
b    40.0
j    50.0
Name: va, dtype: float64

In [10]:
import pandas as pd
import numpy as np
ds=pd.Series({'v':10,'h':20,'a':30,'b':40,'j':50},dtype='float',name='va')
ds

v    10.0
h    20.0
a    30.0
b    40.0
j    50.0
Name: va, dtype: float64

In [11]:
import pandas as pd
import numpy as np
ds=pd.Series(np.array((10,20,30,40,50)),dtype='float',name='va')
ds

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
Name: va, dtype: float64

In [17]:
import pandas as pd
import numpy as np
ds=pd.DataFrame(((10,20,30,40,50),('v','h','a','b','j'),(1,2,3,4,5)),index=['p','q','r'])
ds

    0   1   2   3   4
p  10  20  30  40  50
q   v   h   a   b   j
r   1   2   3   4   5

In [42]:
import pandas as pd
import numpy as np
ds=pd.DataFrame({'name':['V','H','A'],'mark':[1,2,3],'cgpa':[5,6,7]},index=['a','b','c'])
ds

  name  mark  cgpa
a    V     1     5
b    H     2     6
c    A     3     7

In [20]:
import pandas as pd
import numpy as np
ds=pd.DataFrame([{'a':'cc','b':44},{'a':'aa','b':44}])
ds

    a   b
0  cc  44
1  aa  44

In [35]:
import pandas as pd
import numpy as np
df =pd.read_csv('train.csv')
df=df.set_index('Name')
df=df.reset_index()
df

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [36]:
import pandas as pd
import numpy as np
df =pd.read_csv('train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'name':['V','H','A'],'mark':[1,2,3],'cgpa':[5,6,7]},index=['a','b','c'],columns=['name','mark','cgpa'])
df1.set_index('name',drop=True)

      mark  cgpa
name
V        1     5
H        2     6
A        3     7

In [60]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'name':['V','H','A'],'mark':[1,2,3],'cgpa':[5,6,7]},index=['a','b','c'],columns=['name','mark','cgpa'])
df1=df1.set_index('name')
df1.reset_index()

  name  mark  cgpa
0    V     1     5
1    H     2     6
2    A     3     7

In [78]:
import pandas as pd
import numpy as np
df =pd.read_csv('train.csv')
df[['Name','Pclass']]
df.iloc[2:0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [73]:
import pandas as pd
import numpy as np
df =pd.read_csv('train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [79]:
df=df.set_index('Name')

In [120]:
df.loc['Braund, Mr. Owen Harris']

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                   22
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [121]:
df.loc['Braund, Mr. Owen Harris','PassengerId':'Age']

PassengerId       1
Survived          0
Pclass            3
Sex            male
Age              22
Name: Braund, Mr. Owen Harris, dtype: object

In [123]:
df1=pd.DataFrame({'P':[10,20,30],'Q':[20,50,80],'R':[30,60,90]},index=['A','B','C'])

In [139]:
df1

   P  Q  R     D
A  5  5  5   200
B  5  5  5  1000
C  5  5  5  2400

In [131]:
df1.loc['C','R']=88

In [136]:
df1['D']=df1['P']*df1['Q']

In [138]:
df1.loc['A':'C','P':'R']=5