# Create Df from numoy array 8*5

In [3]:
import pandas as pd 
import numpy as np
df =pd.DataFrame(np.random.randint(1,100,(8,5)),columns=['A','B','C','D','E'])


print(df.shape)
print(df.size)
print(df.ndim)


df['Sum']=df['A']+df['B']+df['C']+df['D']+df['E']

df.iloc[5,2]=70

print(df.loc[2:7,'B':'D'])

df.loc[10]=[70,20,50,30,20,200]

(8, 5)
40
2
    B   C   D
2  43  85  89
3  56   3  98
4  47  41  90
5  67  70  92
6  32  56  74
7  50   2  75

In [6]:
df1=pd.DataFrame([['c1','a',2,'v'],['c2','b',3,'h'],['c3','c',4,'a'],['c4','d',5,'v'],['c5','h',6,'a']],columns=['CourseId','CourseName','Credits','Faculty'])
print(df1)
df1=df.set_index('CourseId')
print(df1)
df1.iloc[1,1]=7
df1.loc['c6']=['i',7,'d',1]
print(df1)

  CourseId CourseName  Credits Faculty
0       c1          a        2       v
1       c2          b        3       h
2       c3          c        4       a
3       c4          d        5       v
4       c5          h        6       a

KeyError: "None of ['CourseId'] are in the columns"

In [9]:
df2=pd.read_csv('train.csv')
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# to see head by default 5

In [11]:
df2.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# to see tail by default 5

In [12]:
df2.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [13]:
df2.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# to see random

In [20]:
df2.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
384,385,0,3,"Plotcharsky, Mr. Vasil",male,NaN,0,0,349227,7.8958,NaN,S

In [21]:
df2.sample(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
103,104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
197,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,NaN,S
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
754,755,1,2,"Herman, Mrs. Samuel (Jane Laver)",female,48.0,1,2,220845,65.0000,NaN,S

# info of csv file

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# to give count mean min percentile 25 50 75 and max

In [ ]:
box plot ma percentile ae 25,50,75 che aiya =>

In [23]:
df2.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# describre(include)

In [24]:
df2.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Fortune, Mr. Mark",male,NaN,NaN,NaN,1601,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

# stratical analysis complete

In [26]:
df2.describe(include='object')

                     Name   Sex Ticket    Cabin Embarked
count                 891   891    891      204      889
unique                891     2    681      147        3
top     Fortune, Mr. Mark  male   1601  B96 B98        S
freq                    1   577      7        4      644

# describt(exclude)

In [29]:
df2.describe(exclude="int64")

,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
count,891,891,714.000000,891,891.000000,204,889
unique,891,2,NaN,681,NaN,147,3
top,"Fortune, Mr. Mark",male,NaN,1601,NaN,B96 B98,S
freq,1,577,NaN,7,NaN,4,644
mean,NaN,NaN,29.699118,NaN,32.204208,NaN,NaN
std,NaN,NaN,14.526497,NaN,49.693429,NaN,NaN
min,NaN,NaN,0.420000,NaN,0.000000,NaN,NaN
25%,NaN,NaN,20.125000,NaN,7.910400,NaN,NaN
50%,NaN,NaN,28.000000,NaN,14.454200,NaN,NaN
75%,NaN,NaN,38.000000,NaN,31.000000,NaN,NaN
max,NaN,NaN,80.000000,NaN,512.329200,NaN,NaN

# to change percentile

In [31]:
df2.describe(percentiles=(0.2,0.3,0.8))

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
20%,179.000000,0.000000,1.000000,19.000000,0.000000,0.000000,7.854200
30%,268.000000,0.000000,2.000000,22.000000,0.000000,0.000000,8.050000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
80%,713.000000,1.000000,3.000000,41.000000,1.000000,1.000000,39.687500
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# to see unique value in whole df

# df.nunique() column wise unique values

In [32]:
df2.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

# categarial values?

In [33]:
df2.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# numerical not a catagery

# survive pclass sex and embarked

In [35]:
df2.Sex.unique()

array(['male', 'female'], dtype=object)

In [37]:
df2.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [38]:
df2.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

df2.Ticket.unique() all are unique so all values will be shown

In [40]:
df2.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [41]:
df2.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

# Servied male and female

# total 891 survied 342

In [46]:
df2[df2["Survived"]==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [49]:
df2[df2["Survived"]==1]["Sex"].value_counts()

female    233
male      109
Name: Sex, dtype: int64

In [50]:
df2["Age"]>18

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [51]:
df2[df2["Age"]>18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# pclass 1 2 3 survial count

In [53]:
df2[df2["Survived"]==1]["Pclass"].value_counts()

1    136
3    119
2     87
Name: Pclass, dtype: int64

# Blank Data

In [54]:
df2.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [55]:
df2.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [56]:
df2.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [57]:
data=pd.DataFrame([[1,2,3,np.nan],[4,np.nan,5,np.nan],[7,8,9,10],[1,np.nan,3,4]])
data

   0    1  2     3
0  1  2.0  3   NaN
1  4  NaN  5   NaN
2  7  8.0  9  10.0
3  1  NaN  3   4.0

# to drop nan

In [58]:
data.dropna()

   0    1  2     3
2  7  8.0  9  10.0

In [59]:
data.dropna(how='any')

   0    1  2     3
2  7  8.0  9  10.0

# by default data.dropna(how='any')

In [60]:
data=pd.DataFrame([[1,2,3,np.nan],[4,np.nan,5,np.nan],[7,8,9,10],[1,np.nan,3,4],[np.nan,np.nan,np.nan,np.nan]])
data

     0    1    2     3
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [61]:
data.dropna(how='any')

     0    1    2     3
2  7.0  8.0  9.0  10.0

In [62]:
data.dropna(how='all')

     0    1    2     3
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [64]:
data

     0    1    2     3
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

# numpy x=0 => column  x=1 => row

# pandas ma x=0 => row x=1 => column

In [65]:
data.dropna(axis=0,how='any')

     0    1    2     3
2  7.0  8.0  9.0  10.0

In [66]:
data.dropna(axis=1,how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [67]:
data=pd.DataFrame([[1,2,3,np.nan],[4,np.nan,5,np.nan],[7,8,9,10],[1,np.nan,3,4]])
data

   0    1  2     3
0  1  2.0  3   NaN
1  4  NaN  5   NaN
2  7  8.0  9  10.0
3  1  NaN  3   4.0

In [68]:
data.dropna(axis=1,how='any')

   0  2
0  1  3
1  4  5
2  7  9
3  1  3

In [69]:
data=pd.DataFrame([[1,2,3,np.nan],[4,np.nan,5,np.nan],[7,8,9,10],[1,np.nan,3,4],[np.nan,np.nan,np.nan,np.nan]],columns=["A","B","C","D"])
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [71]:
data.dropna(axis=0,how='any',subset=["A"])

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [72]:
data.dropna(axis=0,how='any',subset=["B"])

     A    B    C     D
0  1.0  2.0  3.0   NaN
2  7.0  8.0  9.0  10.0

In [74]:
data.dropna(axis=0,how='any',subset=["D"])

     A    B    C     D
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [76]:
data.dropna(axis=0,how='any',subset=["B","D"])

     A    B    C     D
2  7.0  8.0  9.0  10.0

In [77]:
data.dropna(axis=0,how='all',subset=["B","D"])

     A    B    C     D
0  1.0  2.0  3.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

# thresh MCQ fav   data.dropna(thresh=2)  2 or 2 thi vadhare fill to j rai or drop

In [79]:
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [80]:
data.dropna(thresh=2)

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [81]:
data.dropna(thresh=3)

     A    B    C     D
0  1.0  2.0  3.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [82]:
data.dropna(thresh=4)

     A    B    C     D
2  7.0  8.0  9.0  10.0

In [83]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# cabin ma data na hoi ae drop

In [87]:
df2.dropna(subset=["Cabin"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [88]:
df2.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [89]:
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

# Fill nan data using mean median and  mode

# if continuos value mean

# middle ma value avti hoi ae na mate median

# frequency hoi tyare mode for category datas

In [91]:
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [92]:
data.fillna(data.mean())

      A    B    C     D
0  1.00  2.0  3.0   7.0
1  4.00  5.0  5.0   7.0
2  7.00  8.0  9.0  10.0
3  1.00  5.0  3.0   4.0
4  3.25  5.0  5.0   7.0

# A mean B median C mode

In [94]:
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [95]:
data["A"]=data["A"].fillna(data["A"].mean())

In [96]:
data

      A    B    C     D
0  1.00  2.0  3.0   NaN
1  4.00  NaN  5.0   NaN
2  7.00  8.0  9.0  10.0
3  1.00  NaN  3.0   4.0
4  3.25  NaN  NaN   NaN

In [97]:
data["B"]=data["B"].fillna(data["B"].median())
data

      A    B    C     D
0  1.00  2.0  3.0   NaN
1  4.00  5.0  5.0   NaN
2  7.00  8.0  9.0  10.0
3  1.00  5.0  3.0   4.0
4  3.25  5.0  NaN   NaN

In [99]:
data["C"]=data["C"].fillna(data["C"].mode())
data

      A    B    C     D
0  1.00  2.0  3.0   NaN
1  4.00  5.0  5.0   NaN
2  7.00  8.0  9.0  10.0
3  1.00  5.0  3.0   4.0
4  3.25  5.0  NaN   NaN

In [100]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [103]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Age fill by mean and Embarked by mode

In [105]:
df2["Age"]=df2["Age"].fillna(df2.Age.mean())

In [106]:
df2.Age.mean()

29.699117647058763

In [108]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Mode ma ans avitna ave che like obj/series but in mean and  mode direct ans ai jai j puct thai jai

In [109]:
df2.Embarked.mode()

0    S
dtype: object

In [110]:
df2.Embarked.mode()[0]

'S'

In [111]:
df2["Embarked"]=df2["Embarked"].fillna(df2.Embarked.mode()[0])

# agar embarked ma [0] karvanu bhuli gya to data type badalai jase

In [112]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [113]:
data

      A    B    C     D
0  1.00  2.0  3.0   NaN
1  4.00  5.0  5.0   NaN
2  7.00  8.0  9.0  10.0
3  1.00  5.0  3.0   4.0
4  3.25  5.0  NaN   NaN

# drop perticular col or row doesn't care if it has null value or not

In [115]:
data.drop(0) #row0

      A    B    C     D
1  4.00  5.0  5.0   NaN
2  7.00  8.0  9.0  10.0
3  1.00  5.0  3.0   4.0
4  3.25  5.0  NaN   NaN

In [117]:
data.drop("B",axis=1)#colB

      A    C     D
0  1.00  3.0   NaN
1  4.00  5.0   NaN
2  7.00  9.0  10.0
3  1.00  3.0   4.0
4  3.25  NaN   NaN

In [118]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

# drop row jema b female avti hoi

In [120]:
df2[(df2["Sex"]=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.000000,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S

In [121]:
df2[(df2["Sex"]!='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.000000,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [127]:
i=df2[df2["Sex"]=='female'].index
df2.drop(i)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.000000,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

# for duplicate data

In [128]:
ds=pd.DataFrame([[1,1,2,3],[2,1,1,3],[1,1,2,3],[2,1,1,3],[1,1,2,2]],index=[7,8,9,10,11],columns=['p','q','r','s'])
ds

    p  q  r  s
7   1  1  2  3
8   2  1  1  3
9   1  1  2  3
10  2  1  1  3
11  1  1  2  2

# to see duplicate value

In [129]:
ds.duplicated()

7     False
8     False
9      True
10     True
11    False
dtype: bool

In [130]:
ds.duplicated().sum()

2

In [132]:
ds.duplicated(subset=["p"])

7     False
8     False
9      True
10     True
11     True
dtype: bool

# by default keep first

In [133]:
ds.drop_duplicates(keep='last')

    p  q  r  s
9   1  1  2  3
10  2  1  1  3
11  1  1  2  2

In [134]:
ds.drop_duplicates()

    p  q  r  s
7   1  1  2  3
8   2  1  1  3
11  1  1  2  2

In [135]:
ds.drop_duplicates(keep='first')

    p  q  r  s
7   1  1  2  3
8   2  1  1  3
11  1  1  2  2

In [136]:
ds.drop_duplicates(subset=["p"])

   p  q  r  s
7  1  1  2  3
8  2  1  1  3

In [137]:
ds.drop_duplicates(subset=["p",'q'])

   p  q  r  s
7  1  1  2  3
8  2  1  1  3