In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
df =pd.read_csv("social_media_engagement.csv")

In [4]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

# Plot bar grapg using plotly

In [5]:
fig=px.bar(data_frame=df,x='post_type',y='likes')
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [6]:
import plotly.io as pio
pio.renderers.default=

In [8]:
fig=px.bar(data_frame=df,x='post_type',y='likes')
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# With data text

In [10]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True)
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# With different colors for different group

In [11]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="platform")
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# Change color colom catagery wise

In [13]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="platform",color_discrete_sequence=["pink","violet","cyan"])
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [14]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="platform",color_discrete_map={"Facebook":"pink","Instagram":"violet","Twitter":"cyan"})
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# change height width

In [16]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="platform",height=700,width=2000,color_discrete_map={"Facebook":"pink","Instagram":"violet","Twitter":"cyan"})
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# title

In [18]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,title="Platform wise post",color="platform",color_discrete_map={"Facebook":"pink","Instagram":"violet","Twitter":"cyan"})
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# color ma numerical col

In [19]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="comments",color_discrete_sequence=["pink","violet","cyan"])
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [21]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="comments",hover_data=["post_day","sentiment_score"],color_discrete_sequence=["pink","violet","cyan"])
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# list in y

In [23]:
fig=px.bar(data_frame=df,x='post_type',y=['likes','comments','shares'],text_auto=True,color="platform",text="comments",color_discrete_sequence=["pink","violet","cyan"])
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# by default barmode="stcak"

In [27]:
fig=px.bar(data_frame=df,x='post_type',y=['likes','comments','shares'],text_auto=True,color="platform",text="comments",color_discrete_sequence=["pink","violet","cyan"],barmode="stack")
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# by group

In [29]:
fig=px.bar(data_frame=df,x='post_type',y=['likes','comments','shares'],text_auto=True,color="platform",color_discrete_sequence=["pink","violet","cyan"],barmode="group")
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# display patern type with categorial col

In [31]:
fig=px.bar(data_frame=df,x='post_type',y=['likes','comments','shares'],text_auto=True,color="platform",color_discrete_sequence=["pink","violet","cyan"],barmode="group",pattern_shape='sentiment_score')
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [32]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

# post day roe col sentiment score

# normal graph

In [34]:
fig=px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,title="Platform wise post",height=1500,width=2000,color="platform",facet_row="post_day",facet_col="sentiment_score",color_discrete_map={"Facebook":"pink","Instagram":"violet","Twitter":"cyan"})
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# scatter graph

In [36]:
px.scatter(data_frame=df,x='likes',y='comments')

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# platform color

In [38]:
px.scatter(data_frame=df,x='likes',y='comments',color='platform')

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# marker shape change

In [40]:
px.scatter(data_frame=df,x='likes',y='comments',color='platform',symbol="post_type")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# group scatter chart

In [41]:
px.scatter(data_frame=df,x='likes',y='comments',color='platform',symbol="platform")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# bubble chart

# bubble chart mate hamesas size=shares

In [44]:
px.scatter(data_frame=df,size='shares',x='likes',y='comments',color='platform',symbol="platform")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [45]:
px.scatter(data_frame=df,size='shares',x='likes',y='comments',color='platform')

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [46]:
px.scatter(data_frame=df,size='shares',x='likes',y='comments',symbol="platform")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [47]:
px.scatter(data_frame=df,size='shares',x='likes',y='comments')

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [48]:
px.scatter(data_frame=df,size='shares',x='likes',y='comments',hover_data=["post_day"],facet_col=df.sentiment_score,facet_row=df.post_day)

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [49]:
px.scatter(data_frame=df,size='shares',x='likes',y='comments',hover_data=["post_day"],facet_col="sentiment_score",facet_row="post_day")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# 3D graph

# 3D ma subplot draw nai thai biju badhu thase

In [53]:
px.scatter_3d(data_frame=df,z='shares',x='likes',y='comments',height=700,width=2000,color="platform")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# scatter_matrix

In [54]:
px.scatter_matrix(data_frame=df,dimensions=["likes","comments","shares"])

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [55]:
px.scatter_matrix(data_frame=df,dimensions=["likes","comments","shares"],color="platform",size="likes")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

# Line chart

# Line chart mate time index or unique index required

In [56]:
px.line(data_frame=df,x="post_id",y="likes")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [57]:
px.line(data_frame=df,x="post_id",y="likes",color="post_type")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [61]:
px.line(data_frame=df,x="post_id",y="likes",color="post_type",markers=True,hover_data=['sentiment_score'])

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [64]:
data=df.groupby("platform",as_index=False)[["likes","comments","shares"]].sum()

In [65]:
data

    platform   likes  comments  shares
0   Facebook   86392      7965   15180
1  Instagram  107994      8368   18906
2    Twitter   43795      3933    7479

# Pie chart

In [67]:
fig=px.pie(data_frame=data,names="platform",values="likes")

In [68]:
fig.show()

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [71]:
fig.update_traces(textinfo="percent+label",textposition="outside",pull=[0.2,0.15,0.1])

In [72]:
df=pd.DataFrame({"dep":["hr","it","hr","it","admin","hr","it"],"salary":[1000,500,700,800,900,1200,1500],"age":[20,25,30,35,22,32,45],"gender":["F","M","F","F","M","F","M"]})

In [73]:
df

     dep  salary  age gender
0     hr    1000   20      F
1     it     500   25      M
2     hr     700   30      F
3     it     800   35      F
4  admin     900   22      M
5     hr    1200   32      F
6     it    1500   45      M

# histogram

In [74]:
px.histogram(data_frame=df,x="age",nbins=10)

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [77]:
px.histogram(data_frame=df,x="dep",y="salary")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [78]:
px.histogram(data_frame=df,x="dep",y="salary",histfunc="max")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [79]:
px.histogram(data_frame=df,x="dep",y="salary",histfunc="avg")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [81]:
px.histogram(data_frame=df,x="dep",y="salary",histfunc="avg",color="gender")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [82]:
px.histogram(data_frame=df,x="dep",y="salary",histfunc="count",color="gender")

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(